### ISSUE TITLE
single file

### ISSUE THREAD

**Issue by ibaned** [SCOREC/scorec-refs#1]
As far as I can tell, the only way for me to include multiple `.bib` files in my thesis is to do this (scorec-refs is a submodule of my repo):

``` latex
\bibliography{scorec-refs/frameworks,scorec-refs/meshdb,...}
```

With no newlines and no spaces in between. Thats going to become a huge ugly line. Could we just put all refs in one files ?

@cwsmith

**Comment by cwsmith** [comment]
I could not find another way to use the multiple bib files either.  Merging them is fine with me.
